2020-03-10 11:34:54,035 INFO: Activity_Viewer startup [in C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\__init__.py:54]
2020-03-10 16:32:21,141 INFO: Activity_Viewer startup [in C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\__init__.py:56]
2020-03-10 16:32:25,071 ERROR: Exception on /index [GET] [in c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\routes.py", line 31, in index
    next_url=next_url, prev_url=prev_url)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\templates\index.html", line 6, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\templates\base.html", line 6, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 12, in block "body"
  File "C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\templates\base.html", line 55, in block "navbar"
    <li><a href="{{ url_for('logout') }}">Logout</a></li>
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'logout'. Did you mean 'auth.logout' instead?
2020-03-10 16:34:33,012 INFO: Activity_Viewer startup [in C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\__init__.py:56]
2020-03-10 16:34:42,048 ERROR: Exception on /auth/login [GET] [in c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\auth\routes.py", line 24, in login
    return render_template('auth/login.html', title='Sign In', form=form)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\templates\auth\login.html", line 5, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\templates\base.html", line 6, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 13, in block "body"
    {%- block styles %}
  File "C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\templates\base.html", line 72, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\templates\auth\login.html", line 14, in block "app_content"
    <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
2020-03-10 16:35:57,758 INFO: Activity_Viewer startup [in C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\__init__.py:56]
